// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCU6XbnToFz7FC-TkelKQdF2xDNfXVhsE',
    appId: '1:571108787345:web:ef9e209c27c7257a9beb30',
    messagingSenderId: '571108787345',
    projectId: 'mynotesabinash27',
    authDomain: 'mynotesabinash27.firebaseapp.com',
    storageBucket: 'mynotesabinash27.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDItt6WahuQ18nxz2g61zpPiMrpNgOVl1Q',
    appId: '1:571108787345:android:bc21c9edd8af37a89beb30',
    messagingSenderId: '571108787345',
    projectId: 'mynotesabinash27',
    storageBucket: 'mynotesabinash27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKdufbWcd0NviHz_VisdwbImMXiBqiOMA',
    appId: '1:571108787345:ios:8d104af6e3a435cd9beb30',
    messagingSenderId: '571108787345',
    projectId: 'mynotesabinash27',
    storageBucket: 'mynotesabinash27.appspot.com',
    iosBundleId: 'com.abinash27052000.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKdufbWcd0NviHz_VisdwbImMXiBqiOMA',
    appId: '1:571108787345:ios:9d16f36d1a3daf0f9beb30',
    messagingSenderId: '571108787345',
    projectId: 'mynotesabinash27',
    storageBucket: 'mynotesabinash27.appspot.com',
    iosBundleId: 'com.abinash27052000.mynotes.RunnerTests',
  );
}
